PARTS_DATA = [
    {
        'id': 1,
        'image' : 'http://localhost:9000/web/parts/1.jpg',
        'name': 'ENGINE SHORT',
        'specification': 'V8 EFI PETROL',
        'oem_number': 'TF-EXH-2024-001',
        'short_description': 'Engine assembly - Short для V8 EFI PETROL.',
        'set_composition': [
            '1. Engine assembly - Short',
        ],
        'dimensions': '90 см х 60 см х 70 см',
        'weight': '200 кг',
    },
    {
        'id': 2,
        'image' : 'http://localhost:9000/web/parts/2.jpg',        
        'name': 'TRANSMISSION BRAKE',
        'specification': 'V8 EFI PETROL',
        'oem_number': 'QX-EXH-2024-005',
        'short_description': 'Transmission brake assembly для V8 EFI PETROL.',
        'set_composition': [
            '1. Drum-transmission brake',
            '2. Screw-disc fixing',
            '3. Backplate-transmission brake assembly',
            '4. Bolt',
            '5. Kit-transmission brake shoe',
            '6. Kit-transmission brake shoe retention',
            '7. Kit-transmission brake adjuster',
            '8. Kit-transmission brake shoe retention',
            '9. Strut-transmission brake',
            '10. Lever-transmission brake',
        ],
        'dimensions': '80 см х 40 см х 30 см',
        'weight': '30 кг',
    },
    {
        'id': 3,
        'image' : 'http://localhost:9000/web/parts/3.jpg',        
        'name': 'TAILPIPE',
        'specification': 'V8 EFI PETROL',
        'oem_number': 'ST-EXH-2024-004',
        'short_description': 'Tailpipe assembly-exhaust system — это сборочный комплект для выхлопной системы, предназначенный для V8 EFI PETROL. Все детали упакованы в прочную коробку, которая оптимизирована для хранения и транспортировки.',
        'set_composition': [
            '1. Tailpipe assembly-exhaust system — основная деталь, представляющая собой выхлопную трубу.',
            '2. Heatshield-exhaust system fuel tank — 10 штук, тепловой щит, защищающий топливный бак от воздействия выхлопных газов.',
            '3. Finisher-trim exhaust tailpipe — 2 штуки, декоративная накладка на выхлопную трубу.',
            '4. Nut - Hex — 3 штуки, шестигранная гайка.',
            '5. Heatshield-rear floor exhaust system — 4 штуки, тепловой щит для защиты заднего пола.',
            '6. Washer — 5 штук, шайбы для распределения давления.',
            '7. Screw — 6 штук, болты для крепления.',
            '8. Nut-flange — 7 штук, фланцевые гайки для надежной фиксации.',
            '9. Mounting-rubber exhaust system — 8 штук, резиновые крепления для амортизации.',
            '10. Heatshield-spare wheel exhaust system — 9 штук, тепловой щит для защиты запасного колеса.',
        ],
        'dimensions': '120 см х 40 см х 50 см',
        'weight': '15 кг',
    },
    {
        'id': 4,
        'image' : 'http://localhost:9000/web/parts/4.jpg',        
        'name': 'FUEL TANK & PARTS',
        'specification': '2.5L 6 CYL DIESEL',
        'oem_number': 'TF-EXH-2024-001',
        'short_description': 'Tank assembly fuel and related parts для 2.5L 6 CYL DIESEL двигателей.',
        'set_composition': [
            '1. Tank assembly fuel',
            '2. Pump-fuel-unit assembly fuel tank',
            '3. Seal-fuel pump unit tank',
            '4. Ring-locking fuel tank',
            '5. Hose assembly-breather fuel',
            '6. Clip-Hose',
            '7. Bracket assembly-fuel tank fuel tank',
            '8. Nut - Hex.',
            '9. Washer-Plain',
            '10. Screw-flanged head',
            '11. Heatshield-fuel tank-exhaust system',
            '12. Sender assembly-fuel tank',
            '13. Screw-heatshield to fuel tank special',
            '14. Insert-hose/pipe support',
            '15. Connector fuel lines',
            '16. Tee piece fuel lines',
        ],
        'dimensions': '150 см х 60 см х 50 см',
        'weight': '40 кг',
    },
    {
        'id': 5,
        'image' : 'http://localhost:9000/web/parts/5.jpg',        
        'name': 'SILL FINISHERS',
        'specification': 'ANY',
        'oem_number': 'TS-EXH-2024-003',
        'short_description': 'Sill finishers для кузова любой конфигурации.',
        'set_composition': [
            '1. Finisher-body side sill',
            '2. Plate-floor cover front sill tread',
            '3. Plate-floor cover rear sill tread',
            '4. Cupsac',
            '5. Clip',
            '6. Rivet-plastic-drive',
            '7. Screw',
            '8. Nutsert-blind',
        ],
        'dimensions': '200 см х 30 см х 10 см',
        'weight': '10 кг',
    },
    {
        'id': 6,
        'image' : 'http://localhost:9000/web/parts/6.jpg',        
        'name': 'FRAME ASSEMBLY',
        'specification': 'V8 EFI PETROL',
        'oem_number': 'DX-EXH-2024-006',
        'short_description': 'Frame assembly для V8 EFI PETROL.',
        'set_composition': [
            '1. Frame assembly-chassis',
            '2. Crossmember-gearbox support',
            '3. Crossmember-front',
            '4. Screw-flanged head',
            '5. Nut-flange',
        ],
        'dimensions': '300 см х 100 см х 50 см',
        'weight': '120 кг',
    }
]